export { LandingHeader } from "./header";
export { LandingHero } from "./hero";
export { LandingFeatures } from "./features";
export { LandingStats } from "./stats";
export { LandingHowItWorks } from "./how-it-works";
export { LandingGallery } from "./gallery";
export { LandingTestimonials } from "./testimonials";
export { LandingCTA } from "./cta";
export { LandingFooter } from "./footer";
