kind = "web"
  previewPath = "/"
  title = "Lopango"
  version = "1.0.0"
  id = "artifacts/lopango"
  router = "path"

  [[integratedSkills]]
  name = "react-vite"
  version = "1.0.0"

  [[services]]
  name = "web"
  paths = [ "/" ]
  localPort = 24203

  [services.development]
  run = "pnpm --filter @workspace/lopango run dev"

  [services.production]

  [services.production.build]
  args = ["pnpm", "--filter", "@workspace/lopango", "run", "build"]

  [services.production.build.env]
  NODE_ENV = "production"

  [services.production.run]
  args = ["pnpm", "--filter", "@workspace/lopango", "run", "start"]

  [services.production.run.env]
  PORT = "24203"
  NODE_ENV = "production"

  [services.env]
  PORT = "24203"
  